# it's-a-me!
name: Stellenbauchery by Julia Burke

# included modules
markdown: redcarpet
pygments: false

# blog configuration
permalink: /blog/:month-:day-:year/:title.html
paginate: 5
paginate_path: 'blog/page:num'
